name: curve-gas-estimates

plugins:
  - name: hardhat
  - name: evm-trace
  - name: etherscan

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: geth

geth:
  ethereum:
    mainnet:
      uri: http://localhost:9090
